//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int Bid_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Sitter_ID { get; set; }
        public Nullable<decimal> ProposedPrice { get; set; }
        public string BidStatus { get; set; }
        public Nullable<System.DateTime> BidDate { get; set; }
    
        public virtual Babysitter Babysitter { get; set; }
        public virtual Job Job { get; set; }
    }
}
