//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CryAlert
    {
        public System.Guid Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Level { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> BabysitterId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
