//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Bids = new HashSet<Bid>();
            this.JobTimeSlots = new HashSet<JobTimeSlot>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int Job_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Child_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime JobDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> AssignedSitter_ID { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string City { get; set; }
    
        public virtual Babysitter Babysitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Child Child { get; set; }
        public virtual Parent Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTimeSlot> JobTimeSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
