//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTimeSlot
    {
        public int JobSlot_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public Nullable<int> Slot_ID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
