//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BabySitterBooking_and_BabyMinderEntities : DbContext
    {
        public BabySitterBooking_and_BabyMinderEntities()
            : base("name=BabySitterBooking_and_BabyMinderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Babysitter> Babysitters { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobTimeSlot> JobTimeSlots { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<SitterAvailability> SitterAvailabilities { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<CryAlert> CryAlerts { get; set; }
    }
}
