//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public int Reviewer_ID { get; set; }
        public string ReviewerRole { get; set; }
        public int ReviewFor_ID { get; set; }
        public string ReviewForRole { get; set; }
        public decimal Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
