//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitterAvailability
    {
        public int Availability_ID { get; set; }
        public Nullable<int> Sitter_ID { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public Nullable<int> Slot_ID { get; set; }
        public string City { get; set; }
    
        public virtual Babysitter Babysitter { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
